services:
  postgres:
    container_name: postgres-taxi
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: modsen-taxi-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin-ui-taxi
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: pdfmain.user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

volumes:
  pgadmin-data:
  pgdata:

networks:
  postgres:
    driver: bridge