spring:
  application:
    name: e2e-service

app:
  api:
    feign:
      clients:
        rides:
          name: rides-service
          routes:
            book-ride: /public/api/v1/rides/passengers/{passengerExternalId}
            start-ride: /public/api/v1/rides/{rideExternalId}/drivers/{driverExternalId}/start
            finish-ride: /public/api/v1/rides/{rideExternalId}/drivers/{driverExternalId}/finish
            find-ride-by-passenger-external-id: /public/api/v1/rides/{rideExternalId}/passengers/{passengerExternalId}
        driver:
          name: driver-service
          routes:
            find-driver-by-external-id: /public/api/v1/drivers/{driverExternalId}