server:
  port: 8082

spring:
  application:
    name: rides-service

  liquibase:
    change-log: db/changelog/main-changelog.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/taxi-rides
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false
        show_sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rides-service-group
      auto-offset-reset: earliest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  config:
    base-cost-per-km: 1

  kafka:
    topic:
      ride-info-events: ride-info-events
      driver-status-events: driver-status-events
      driver-info-events: driver-info-events
      ride-payment-events: ride-payment-events
      payment-result: payment-result

  api:
    feign:
      clients:
        passenger:
          name: passenger-service
          routes:
            get-payment-method: /public/api/v1/passengers/{externalId}/paymentMethod
        card:
          name: card-service
          routes:
            get-default-card: /public/api/v1/passengers/{passengerExternalId}/cards/default