server:
  port: 8084

spring:
  application:
    name: payment-service

  liquibase:
    change-log: db/changelog/main-changelog.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/taxi-card-balances
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false
        show_sql: false

  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    function:
      definition: consumeCardInfo;processRidePayment
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092

      bindings:
        consumeCardInfo-in-0:
          destination: new-card-details
          group: payment-service

        processRidePayment-in-0:
          destination: ride-payment-events
          group: payment-service

        processRidePayment-out-0:
          destination: payment-result

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
