server:
  port: 8084

spring:
  application:
    name: payment-service

  liquibase:
    change-log: db/changelog/main-changelog.xml
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/taxi-card-balances
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false
        show_sql: false

  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    function:
      definition: consumeCardInfo
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        consumeCardInfo-in-0:
          destination: new-card-details
          group: payment-service
