server:
  port: 8081

spring:
  application:
    name: driver-service

  liquibase:
    change-log: db/changelog/main-changelog.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/taxi-drivers
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false
        show_sql: false

  messages:
    basename: messages-constants

app:
  api:
    web-client:
      connection-timeout-in-ms: 1000

  routes:
    rides:
      accept-ride-method: http://localhost:8082/public/api/v1/rides/{rideExternalId}/drivers/{driverExternalId}/accept