server:
  port: 8080

spring:
  application:
    name: passenger-service

  liquibase:
    change-log: db/changelog/main-changelog.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/modsen-taxi-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

