server:
  port: 8080

spring:
  application:
    name: passenger-service

  liquibase:
    change-log: db/changelog/main-changelog.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://postgres:5432/modsen-taxi-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        show_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: passenger-service-group
      auto-offset-reset: earliest

  messages:
    basename: messages-constants

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaservice:8761/eureka/

app:
  kafka:
    topic:
      payment-method-details: payment-method-details
      card-default-status-details: card-default-status-details
      new-passenger-details: new-passenger-details
      removed-passenger-details: removed-passenger-details
      error-card-details: error-card-details

logging:
  level:
    web: INFO