server:
  port: 8083

spring:
  application:
    name: card-service

#  liquibase:
#    change-log: db/changelog/main-changelog.xml
#    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/taxi-cards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        show_sql: true

  messages:
    basename: messages-constants


app:
  api:
    feign-client:
      passenger:
        name: passenger-service
        url: localhost:8080/public/api/v1/
        endpoints:
          findByExternalId: passengers/{externalId}



logging:
  level:
    web: INFO